"""subir cambios a la db

Revision ID: 385967a2e00c
Revises: f85b30bc1c50
Create Date: 2022-09-21 12:14:39.138311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385967a2e00c'
down_revision = 'f85b30bc1c50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('creacion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estudios', 'creacion')
    # ### end Alembic commands ###
