"""subir cambios a la db

Revision ID: 59c9085173ef
Revises: cb00e968ecc0
Create Date: 2022-09-21 11:50:11.629883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c9085173ef'
down_revision = 'cb00e968ecc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('estudios', sa.String(), nullable=True))
    op.drop_column('estudios', 'estudio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('estudio', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('estudios', 'estudios')
    # ### end Alembic commands ###
