"""subir cambios a la db

Revision ID: 7055159fb0c0
Revises: 84b7949f033c
Create Date: 2022-09-21 12:08:48.055793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7055159fb0c0'
down_revision = '84b7949f033c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('estudio', sa.String(), nullable=True))
    op.drop_column('estudios', 'estudio_realizado')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('estudio_realizado', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('estudios', 'estudio')
    # ### end Alembic commands ###
