"""subir cambios a la db

Revision ID: 7baa42fbaf91
Revises: 59c9085173ef
Create Date: 2022-09-21 11:51:53.907716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7baa42fbaf91'
down_revision = '59c9085173ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('estudio_realizado', sa.String(), nullable=True))
    op.drop_column('estudios', 'estudios')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estudios', sa.Column('estudios', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('estudios', 'estudio_realizado')
    # ### end Alembic commands ###
