"""subir cambios a la db

Revision ID: 84b7949f033c
Revises: 7baa42fbaf91
Create Date: 2022-09-21 12:00:17.384731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b7949f033c'
down_revision = '7baa42fbaf91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
