"""subir cambios a la db

Revision ID: e0dcca1551c0
Revises: 385967a2e00c
Create Date: 2022-09-21 12:15:57.498673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0dcca1551c0'
down_revision = '385967a2e00c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
